theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
title: 一切如常|2020高中生音乐节
description: To advertize our live
logo: ./src/images/Luna.jpg
show_downloads: false
google_analytics: UA-173140490-2